#pragma once

#include "utils/utils.hpp"

_IMPLEMENT_SCOPE

namespace http{

	enum status{
		//100 ~ 103 -> 상태 정보 제공
		CONTINUE = 100,
		SWITCHING_PROTOCOLS,
		PROCESSING,
		EARLY_HINTS,

		//200 ~ 208 -> 성공관련 상태
		OK = 200,
		CREATED,
		ACCEPTED,
		NON_AUTORITATIVE_INFO,
		NO_CONTENT,
		RESET_CONTENT,
		PARTIAL_CONTENT,
		MULTI_STATUS,
		ALREADY_REPORTED,
		IM_USED = 226,

		//300 ~ 308 -> 리다이렉션
		MULTIPLLE_CHOICES = 300,
		MOVED_PERMANENTLY,
		FOUND,
		SEE_OTHER,
		NOT_MODIFIED,
		USE_PROXY,
		TEMPORARY_REDIRECT = 307,
		PERMANENT_REDIRECT,

		//400~ -> 클라이언트 에러
		BAD_REQUEST = 400,
		UNAUTHORIZED,
		PAYMENT_REQUIRED,
		FORBIDDEN,
		NOT_FOUND,
		METHOD_NOT_ALLOWED,
		NOT_ACCEPTABLE,
		PROXY_AUTHENTICATION_REQUIRED,
		REQUEST_TIMEOUT,
		CONFLICT,
		GONE,
		LENGTH_REQUIRED,
		PRECONDITION_FAILED,
		PAYLOAD_TOO_LARGE,
		URI_TOO_LONG,
		UNSUPPORTED_MEDIA_TYPE,
		RANGE_NOT_SATISFIABLE,
		EXPECTATION_FAILED,
		MISDIRECTED_REQUEST = 421,
		UNPROCESSABLE_ENTITY,
		LOCKED,
		FAILED_DEPENDENCY,
		UPGRADE_REQUIRED = 426,
		PRECONDITION_REQUIRED = 428,
		TOO_MANY_REQUESTS,
		REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
		UNAVAILABLE_FOR_LEGAL_REASONS = 451,

		//500 -> server error
		INTERNAL_SERVER_ERROR = 500,
		NOT_IMPLEMENTED,
		BAD_GATEWAY,
		SERVICE_UNAVAILABLE,
		GATEWAY_TIMEOUT,
		HTTP_VERSION_NOT_SUPPORTED,
		VARIANT_ALSO_NEGOTIATES,
		INSUFFICIENT_STORAGE,
		LOOP_DETECTED,
		NOT_EXTENDED = 510,
		NETWORK_AUTHENTICATION_REQUIRED
	};

}

_IMPLEMENT_END